### ISSUE TITLE
Shadowing checklist

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#9]
It turned out that the theme does not support shadowing. In consequence this means this repo has to be used as a starter, not like a theme. This lists summarizes what works w.r.t. shadowing and what does not yet:

- [x] Shadowing of favicon (via `demo/static/images/favicon.png`) https://github.com/NK-WebDev/gatsby-theme-teranova/pull/13
- [x] Shadowing of themes.js (via `demo/src/gatsby-theme-teranova/theme.js`), but wrong instructions https://github.com/NK-WebDev/gatsby-theme-teranova/issues/8
- [x] Shadowing of index.mdx (via `src/gatsby-theme-teranova/pages/index.mdx`), but wrong instructions https://github.com/NK-WebDev/gatsby-theme-teranova/issues/11
- [x] Shadowing of about, services, etc. sections
- [x] Shadowing of index.js https://github.com/NK-WebDev/gatsby-theme-teranova/issues/7
- [x] Shadowing of navbar.js (for adding custom sections) https://github.com/NK-WebDev/gatsby-theme-teranova/pull/14

**Comment by fkromer** [comment]
demo seems to be published to netlify. The builds of the PRs fail for some reasons I don't know. A customization demo could be placed into `customized-demo` and the PRs adjusted from `demo` to `customized-demo`. Would help people understand theme usage for sure.

**Comment by fkromer** [comment]
@NK-WebDev After fixing this you can get rid of the whole `gatsby-theme-teranova` directory in https://github.com/NK-WebDev/geonepal :wink:

**Comment by fkromer** [comment]
A workaround to use the theme as a starter is e.g. to modify the theme files in directory `gatsby-theme-teranova` and define the modified theme as dependency in the demo config via `"gatsby-theme-teranova": "file:../gatsby-theme-teranova",`.

**Comment by nirjan-dev** [comment]
The mdx files can be shadowed if it is imported directly and used as a component instead of the mdx renderer, the data folder also has to be moved inside the src folder, I'm still working on making some more stuff easier to customize, I'll probably finish it at the weekend.

**Comment by fkromer** [comment]
@NK-WebDev Cause your theme does not work like themes usually work w.r.t. shadowing it would be great if you could (A) either provide detailed instructions about how to use your theme and state that it is a starter and not a theme or (B) modify the theme to make it work like one would expect a theme to work :wink: . Unfortunately I'm not able to help out with this.

**Comment by nirjan-dev** [comment]
That's alright, I'm gonna change it soon so shadowing works as expected, I've been looking at the source code of some the [themes by lekoarts](https://themes.lekoarts.de/) and I've decided to follow a similar structure to make it easier for users.

**Comment by nirjan-dev** [comment]
hey @fkromer, can you take a look at [this branch](https://github.com/NK-WebDev/gatsby-theme-teranova/tree/feature/dynamic-content), I've made some changes that make it easier to change the theme content.
- the theme now uses [theme options](https://www.gatsbyjs.org/docs/theme-api/#configuration) for configuration
- all the previous stuff in the siteMetadata can now be passed in as options to the theme plus an extra option called contentFolder which is the path to where you want to put the content for the theme
- all of the options have a default option set using a function in the utils/default-options.js file so none of the options are required for now
- there's a gatsby-node file that copies all the content required for the theme to the contentFolder path
- the mdx files copied to the contentFolder path can be edited and the theme will update accordingly
- the homepage is also generated using the layout.js component so the pages folder is not required, to edit the structure of the homepage you can just shadow the layout component

Let me know if there are any issues in the branch if there are no issues then after updating the docs I can finally close this issue.

**Comment by fkromer** [comment]
@NK-WebDev Do you know when you will merge into master already?

**Comment by nirjan-dev** [comment]
@fkromer I've been a bit busy recently, I was hoping to do some design changes as well and then release a new major version of the theme but that seems unlikely now so I guess I will merge it into master and release 2.0.0 tomorrow after updating the docs. Have you found any bugs in this branch?

**Comment by fkromer** [comment]
@NK-WebDev I've just had a look onto the commits. However it was not clear to me how one can customize the theme. I've not tried something out yet.

**Comment by nirjan-dev** [comment]
@fkromer When the gatsby develop command is run from the demo it will generate a folder with the mdx files and then you can just edit those mdx files, If you want to customize other things then use the options in the gatsby-config of the demo 
```js
resolve: 'gatsby-theme-teranova',
option: {
	// accepts all the option that was previously passed using siteMetadata
}

**Comment by nirjan-dev** [comment]
@fkromer  Version 2.0.0 has been released which fixes this issue

**Comment by fkromer** [comment]
@NK-WebDev Great, thanks a lot!
